# This file was generated by GoReleaser. DO NOT EDIT.
cask "shrink" do
  version "1.1.1"

  on_macos do
    on_intel do
      sha256 "db24faf035a6ac453d77281523207e3780569b2aa8acf703c86e8ea5b54531f1"
      url "https://github.com/desaianand1/shrink-releases/releases/download/v#{version}/shrink_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/desaianand1/shrink-releases/"
    end
    on_arm do
      sha256 "76c3035370d637a9d3755105fe1c2af524e59f741cd98bae9ed5e758a7d483da"
      url "https://github.com/desaianand1/shrink-releases/releases/download/v#{version}/shrink_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/desaianand1/shrink-releases/"
    end
  end

  on_linux do
    on_intel do
      sha256 "6f272d4010d71f250f281a6dcc589c42b48d0dd7c9c278ab3b54d87f9186bcf6"
      url "https://github.com/desaianand1/shrink-releases/releases/download/v#{version}/shrink_#{version}_linux_amd64.tar.gz",
        verified: "github.com/desaianand1/shrink-releases/"
    end
    on_arm do
      sha256 "99e2219156ef6365588e9c632aacc7256cd1dbd0b35bad6cb2c29a017fa30881"
      url "https://github.com/desaianand1/shrink-releases/releases/download/v#{version}/shrink_#{version}_linux_arm64.tar.gz",
        verified: "github.com/desaianand1/shrink-releases/"
    end
  end

  name "shrink"
  desc "Local-first CLI tool to minimize, convert, and batch-process files"
  homepage "https://github.com/desaianand1/shrink-releases"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "ffmpeg",
      "ghostscript",
      "imagemagick",
    ]

  binary "shrink"
  bash_completion "completions/shrink.bash"
  fish_completion "completions/shrink.fish"
  zsh_completion "completions/shrink.zsh"

  # No zap stanza required

  caveats <<~EOS
    shrink uses external tools for file processing. Run:
      shrink doctor
    to check which tools are available, and:
      shrink doctor --install
    to install missing dependencies via your package manager.
  EOS
end
