# This file was generated by GoReleaser. DO NOT EDIT.
cask "shrink" do
  version "1.2.0"

  on_macos do
    on_intel do
      sha256 "75c944e066c8a7845f27278c4244f373fe9f86da3353b82572c3c227d50baa51"
      url "https://github.com/desaianand1/shrink-releases/releases/download/v#{version}/shrink_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/desaianand1/shrink-releases/"
    end
    on_arm do
      sha256 "748b83936981f634316e2cceabf352b8e15e0300538f92215dd1857443061830"
      url "https://github.com/desaianand1/shrink-releases/releases/download/v#{version}/shrink_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/desaianand1/shrink-releases/"
    end
  end

  on_linux do
    on_intel do
      sha256 "978f4e56435849a81c07478aa4d6e7d668c33eb3505f7eaf561dfa2c0f7a6633"
      url "https://github.com/desaianand1/shrink-releases/releases/download/v#{version}/shrink_#{version}_linux_amd64.tar.gz",
        verified: "github.com/desaianand1/shrink-releases/"
    end
    on_arm do
      sha256 "7136075498e1a7ee65bd90946cdfc60a68fa24757d43d2e8e801d56490962ee1"
      url "https://github.com/desaianand1/shrink-releases/releases/download/v#{version}/shrink_#{version}_linux_arm64.tar.gz",
        verified: "github.com/desaianand1/shrink-releases/"
    end
  end

  name "shrink"
  desc "Local-first CLI tool to minimize, convert, and batch-process files"
  homepage "https://github.com/desaianand1/shrink-releases"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "ffmpeg",
      "ghostscript",
      "imagemagick",
    ]

  binary "shrink"
  bash_completion "completions/shrink.bash"
  fish_completion "completions/shrink.fish"
  zsh_completion "completions/shrink.zsh"

  # No zap stanza required

  caveats <<~EOS
    shrink uses external tools for file processing. Run:
      shrink doctor
    to check which tools are available, and:
      shrink doctor --install
    to install missing dependencies via your package manager.
  EOS
end
