# This file was generated by GoReleaser. DO NOT EDIT.
cask "shrink" do
  version "1.3.1"

  on_macos do
    on_arm do
      sha256 "d2402ff12020640666afe0af32c3288c4a36968b5f8f96b23b5450eec82807b9"
      url "https://github.com/desaianand1/shrink-releases/releases/download/v#{version}/shrink_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e0809f7cd33547b5f115d0a2af7215bd91eac3238141c2544a981aae2534c255"
      url "https://github.com/desaianand1/shrink-releases/releases/download/v#{version}/shrink_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "093eb62149b087fa17e1335a32955720e91f677000d5d3f303ff382e13093bd5"
      url "https://github.com/desaianand1/shrink-releases/releases/download/v#{version}/shrink_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "22117a9bc479a84c5108cb560c7263ba7523007ae90a326ba7149f0ddda7cc24"
      url "https://github.com/desaianand1/shrink-releases/releases/download/v#{version}/shrink_#{version}_linux_amd64.tar.gz"
    end
  end

  name "shrink"
  desc "Local-first CLI tool to minimize, convert, and batch-process files"
  homepage "https://github.com/desaianand1/shrink-releases"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "ffmpeg",
      "ghostscript",
      "imagemagick",
    ]

  binary "shrink"
  bash_completion "completions/shrink.bash"
  fish_completion "completions/shrink.fish"
  zsh_completion "completions/shrink.zsh"

  # No zap stanza required

  caveats <<~EOS
    shrink uses external tools for file processing. Run:
      shrink doctor
    to check which tools are available, and:
      shrink doctor --install
    to install missing dependencies via your package manager.
  EOS
end
