# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shrink < Formula
  desc "Local-first CLI tool to minimize, convert, and batch-process files"
  homepage "https://github.com/desaianand1/shrink"
  version "1.0.0"
  license "MIT"

  depends_on "ffmpeg" => :recommended
  depends_on "ghostscript" => :recommended
  depends_on "imagemagick" => :recommended
  depends_on "jpegoptim" => :optional
  depends_on "jq" => :optional
  depends_on "pandoc" => :optional
  depends_on "pngquant" => :optional
  depends_on "qpdf" => :optional
  depends_on "webp" => :optional
  depends_on "yq" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/desaianand1/shrink/releases/download/v1.0.0/shrink_1.0.0_darwin_amd64.tar.gz"
      sha256 "f6bd3c127b97fd047699923d4ea9fb8f2427c8a882314102b2e72dd57dfa57a1"

      define_method(:install) do
        bin.install "shrink"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/desaianand1/shrink/releases/download/v1.0.0/shrink_1.0.0_darwin_arm64.tar.gz"
      sha256 "e79b451986e877da53f6ad964def487ac80251b6433dbbdf4a70a0ab06408153"

      define_method(:install) do
        bin.install "shrink"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/desaianand1/shrink/releases/download/v1.0.0/shrink_1.0.0_linux_amd64.tar.gz"
      sha256 "5c65a63a311028e8c9493bac70c13773efa65c19259a034740f54c2f79c982bd"
      define_method(:install) do
        bin.install "shrink"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/desaianand1/shrink/releases/download/v1.0.0/shrink_1.0.0_linux_arm64.tar.gz"
      sha256 "34f04a14b93a2b156c16e1dbb9a24a77dbe56f5463317fcd5c3e8ade6085f4e5"
      define_method(:install) do
        bin.install "shrink"
      end
    end
  end

  test do
    system "#{bin}/shrink", "--version"
  end
end
