# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shrink < Formula
  desc "Local-first CLI tool to minimize, convert, and batch-process files"
  homepage "https://github.com/desaianand1/shrink-releases"
  version "1.1.0"

  depends_on "basictex" => :optional
  depends_on "ffmpeg" => :recommended
  depends_on "ghostscript" => :recommended
  depends_on "imagemagick" => :recommended
  depends_on "jpegoptim" => :optional
  depends_on "jq" => :optional
  depends_on "pandoc" => :optional
  depends_on "pngquant" => :optional
  depends_on "qpdf" => :optional
  depends_on "webp" => :optional
  depends_on "yq" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/desaianand1/shrink-releases/releases/download/v1.1.0/shrink_1.1.0_darwin_amd64.tar.gz"
      sha256 "108d840acd8bdb36d045a6d06662bfc98984cafb057622b0d732c6ef9d7f12ac"

      define_method(:install) do
        bin.install "shrink"
        bash_completion.install "completions/shrink.bash" => "shrink"
        zsh_completion.install "completions/shrink.zsh" => "_shrink"
        fish_completion.install "completions/shrink.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/desaianand1/shrink-releases/releases/download/v1.1.0/shrink_1.1.0_darwin_arm64.tar.gz"
      sha256 "a0e2755dadf72ac2fd4957855b9ca69cf6aad680d8255ac4ca236556ae598b76"

      define_method(:install) do
        bin.install "shrink"
        bash_completion.install "completions/shrink.bash" => "shrink"
        zsh_completion.install "completions/shrink.zsh" => "_shrink"
        fish_completion.install "completions/shrink.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/desaianand1/shrink-releases/releases/download/v1.1.0/shrink_1.1.0_linux_amd64.tar.gz"
      sha256 "ebe47921cc87c4df3da68f64c2b457f1d4e37f014716c69f05d72208032a31be"
      define_method(:install) do
        bin.install "shrink"
        bash_completion.install "completions/shrink.bash" => "shrink"
        zsh_completion.install "completions/shrink.zsh" => "_shrink"
        fish_completion.install "completions/shrink.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/desaianand1/shrink-releases/releases/download/v1.1.0/shrink_1.1.0_linux_arm64.tar.gz"
      sha256 "d5b6e43815be34c5ec8e5efcc847f4fbc658c7ebfeac3adfa1135496ce9ee052"
      define_method(:install) do
        bin.install "shrink"
        bash_completion.install "completions/shrink.bash" => "shrink"
        zsh_completion.install "completions/shrink.zsh" => "_shrink"
        fish_completion.install "completions/shrink.fish"
      end
    end
  end

  def caveats
    <<~EOS
      shrink uses external tools for file processing. Run:
        shrink doctor
      to check which tools are available, and:
        shrink doctor --install
      to install missing dependencies via your package manager.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/shrink version")
    assert_match "doctor", shell_output("#{bin}/shrink --help")
  end
end
